apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: limit-body-size
  namespace: {{ .Release.Namespace }}
spec:
  buffering:
    maxRequestBodyBytes: 2000000  # Example: Limit request body size to 2MB
